# Generated by Django 3.0.3 on 2020-07-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('content', models.CharField(max_length=200, verbose_name='信息内容')),
                ('timestamp', models.DateField(auto_now=True, verbose_name='反馈时间')),
            ],
            options={
                'verbose_name': '信息反馈表',
                'verbose_name_plural': '信息反馈表',
            },
        ),
    ]
